// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: css_variables.sql

package db

import (
	"context"
)

const getCSSVariableByName = `-- name: GetCSSVariableByName :one
SELECT name, value, variable_type, is_system, created_at, updated_at FROM css_variables WHERE name = $1
`

func (q *Queries) GetCSSVariableByName(ctx context.Context, name string) (CssVariable, error) {
	row := q.db.QueryRow(ctx, getCSSVariableByName, name)
	var i CssVariable
	err := row.Scan(
		&i.Name,
		&i.Value,
		&i.VariableType,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
