// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleUser      UserRole = "user"
	UserRoleModerator UserRole = "moderator"
	UserRoleAdmin     UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DigitalAsset struct {
	ID            pgtype.UUID        `json:"id"`
	VariantID     pgtype.UUID        `json:"variant_id"`
	Name          string             `json:"name"`
	FilePath      string             `json:"file_path"`
	FileSize      *int64             `json:"file_size"`
	ContentType   *string            `json:"content_type"`
	DownloadCount int32              `json:"download_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	IsActive    bool               `json:"is_active"`
	IsDigital   bool               `json:"is_digital"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ProductCategory struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type ProductKey struct {
	ID        pgtype.UUID        `json:"id"`
	VariantID pgtype.UUID        `json:"variant_id"`
	KeyValue  string             `json:"key_value"`
	IsUsed    bool               `json:"is_used"`
	OrderID   pgtype.UUID        `json:"order_id"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProductOption struct {
	ID        pgtype.UUID `json:"id"`
	ProductID pgtype.UUID `json:"product_id"`
	Name      string      `json:"name"`
	Position  int32       `json:"position"`
}

type ProductOptionValue struct {
	ID       pgtype.UUID `json:"id"`
	OptionID pgtype.UUID `json:"option_id"`
	Value    string      `json:"value"`
	Position int32       `json:"position"`
}

type ProductVariant struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	Sku           *string            `json:"sku"`
	Price         pgtype.Numeric     `json:"price"`
	StockQuantity int32              `json:"stock_quantity"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Username        *string            `json:"username"`
	HashedPassword  string             `json:"hashed_password"`
	FirstName       *string            `json:"first_name"`
	LastName        *string            `json:"last_name"`
	FullName        *string            `json:"full_name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	Role            UserRole           `json:"role"`
	IsEmailVerified bool               `json:"is_email_verified"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type VariantOptionValue struct {
	VariantID     pgtype.UUID `json:"variant_id"`
	OptionValueID pgtype.UUID `json:"option_value_id"`
}
