// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetCSSVariableByName(ctx context.Context, name string) (CssVariable, error)
}

var _ Querier = (*Queries)(nil)
